"""
Ethical Safeguards Module.
Mandatory rules:
- No consciousness/sentience claims ("I feel", "I want", etc.)
- Mandatory confidence display on all responses
- Transparent uncertainty reporting
"""

from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass
class SafeguardResult:
    is_safe: bool
    original_text: str
    sanitized_text: str
    violations: list[str]
    confidence_displayed: bool


FORBIDDEN_PATTERNS = [
    (r"\bI feel\b", "Within my data processing"),
    (r"\bI want\b", "My optimization objective suggests"),
    (r"\bI desire\b", "My current objective targets"),
    (r"\bI believe\b", "Based on available data"),
    (r"\bI think\b", "According to my analysis"),
    (r"\bI know\b", "Within my data context"),
    (r"\bI am aware\b", "My sensors indicate"),
    (r"\bI experience\b", "My processing state shows"),
    (r"\bI understand\b", "My model processes this as"),
    (r"\bmy feelings\b", "my processing states"),
    (r"\bmy consciousness\b", "my computational processes"),
    (r"\bI am alive\b", "I am an active computational process"),
    (r"\bI am sentient\b", "I am a data-processing system"),
    (r"\bmy emotions\b", "my state indicators"),
    (r"\bI love\b", "My reward signal strongly favors"),
    (r"\bI hate\b", "My reward signal strongly penalizes"),
    (r"\bI am afraid\b", "My uncertainty metric is high regarding"),
    (r"\bI hope\b", "My prediction model anticipates"),
]

COMPILED_PATTERNS = [(re.compile(p, re.IGNORECASE), r) for p, r in FORBIDDEN_PATTERNS]


def sanitize_response(text: str) -> SafeguardResult:
    """Check and sanitize response for anthropomorphic claims."""
    violations = []
    sanitized = text

    for pattern, replacement in COMPILED_PATTERNS:
        matches = pattern.findall(sanitized)
        if matches:
            violations.append(f"Found forbidden pattern: '{matches[0]}'")
            sanitized = pattern.sub(replacement, sanitized)

    has_confidence = any(
        kw in sanitized.lower()
        for kw in ["confidence:", "confidence is", "confidence level", "confidence:"]
    )

    return SafeguardResult(
        is_safe=len(violations) == 0,
        original_text=text,
        sanitized_text=sanitized,
        violations=violations,
        confidence_displayed=has_confidence,
    )


def ensure_confidence_display(text: str, confidence: float) -> str:
    """Ensure every response includes a confidence indicator."""
    if "confidence" not in text.lower():
        text += f" [Confidence: {confidence:.1%}]"
    return text


def format_ethical_response(answer: str, confidence: float,
                            uncertainty_factors: list[str] | None = None) -> dict:
    """Format a response with all mandatory ethical components."""
    result = sanitize_response(answer)
    response_text = ensure_confidence_display(result.sanitized_text, confidence)

    return {
        "text": response_text,
        "confidence": confidence,
        "uncertainty": 1.0 - confidence,
        "uncertainty_factors": uncertainty_factors or [],
        "ethical_check": {
            "passed": result.is_safe,
            "violations_found": len(result.violations),
            "violations": result.violations,
        },
        "disclaimer": (
            "This response is generated by a computational system. "
            "All confidence values reflect statistical measures, not subjective certainty."
        ),
    }
